all:
	@echo ---- compiling by jdk6 --------------------------------
	/home/opt/jdk1.6.0_45/bin/javac ServerProtocolTest.java
	@echo ---- run by jdk6 --------------------------------------
	/home/opt/jdk1.6.0_45/bin/java ServerProtocolTest
	@echo ---- run by jdk7 --------------------------------------
	/home/opt/jdk1.7.0_80/bin/java ServerProtocolTest
	@echo ---- run by jdk8 --------------------------------------
	/home/opt/jdk1.8.0_51/bin/java ServerProtocolTest
